---
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: "Create a Storage Account"
      azure_rm_storageaccount:
        resource_group: BUYDEV1NDXNISRG-APP
        name: "{{ strname }}"
        type: Standard_RAGRS

